/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.BorderLayout;

/**
 *
 * @author josearielpereyra
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    PanelDeDibujo panelDeDibujo = new PanelDeDibujo();
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        add(panelDeDibujo, BorderLayout.CENTER);
        configurarMenuFiguras();
        configurarMenuColor();
        setLocationRelativeTo(null);
    }

    private void configurarMenuColor() {
        javax.swing.JMenuItem itemElegirColor = new javax.swing.JMenuItem("Elegir color...");
        itemElegirColor.addActionListener(e -> {
            java.awt.Color colorElegido = javax.swing.JColorChooser.showDialog(
                    this, "Elegir color", java.awt.Color.BLACK);
            if (colorElegido != null) {
                panelDeDibujo.setColorSeleccionado(colorElegido);
            }
        });
        jMenu5.add(itemElegirColor);
    }

    private void configurarMenuFiguras() {
        javax.swing.JRadioButtonMenuItem itemLinea = new javax.swing.JRadioButtonMenuItem("Línea");
        javax.swing.JRadioButtonMenuItem itemTrazo = new javax.swing.JRadioButtonMenuItem("Trazo");
        javax.swing.JRadioButtonMenuItem itemRectangulo = new javax.swing.JRadioButtonMenuItem("Rectángulo");
        javax.swing.JRadioButtonMenuItem itemRectanguloRelleno = new javax.swing.JRadioButtonMenuItem("Rectángulo relleno");

        itemLinea.setSelected(true);

        javax.swing.ButtonGroup grupoFiguras = new javax.swing.ButtonGroup();
        grupoFiguras.add(itemLinea);
        grupoFiguras.add(itemTrazo);
        grupoFiguras.add(itemRectangulo);
        grupoFiguras.add(itemRectanguloRelleno);

        itemLinea.addActionListener(e -> panelDeDibujo.setTipoSeleccionado(figuras.Figura.TipoFigura.LINEA));
        itemTrazo.addActionListener(e -> panelDeDibujo.setTipoSeleccionado(figuras.Figura.TipoFigura.TRAZO));
        itemRectangulo.addActionListener(e -> panelDeDibujo.setTipoSeleccionado(figuras.Figura.TipoFigura.RECTANGULO));
        itemRectanguloRelleno.addActionListener(e -> panelDeDibujo.setTipoSeleccionado(figuras.Figura.TipoFigura.RECTANGULO_RELLENO));

        jMenu4.add(itemLinea);
        jMenu4.add(itemTrazo);
        jMenu4.add(itemRectangulo);
        jMenu4.add(itemRectanguloRelleno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sin Nombre - Paint");

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Figura");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Color");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 573, 411);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
